import unittest
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

BASE_URL = "http://127.0.0.1:5000"

class TestWebAppSelenium(unittest.TestCase):

    def setUp(self):
        # Запускаємо браузер перед кожним тестом і розгортаємо на весь екран
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        self.driver.maximize_window()
        self.driver.implicitly_wait(5) 

    def tearDown(self):
        # Закриваємо браузер після завершення тесту
        if self.driver:
            self.driver.quit()

    def login_user(self, email, password):
        # Заходимо на сторінку входу, вводимо дані і тиснемо кнопку
        self.driver.get(f"{BASE_URL}/login")
        self.driver.find_element(By.ID, "email").send_keys(email)
        self.driver.find_element(By.ID, "password").send_keys(password)
        self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        
        # Чекаємо, поки з'явиться повідомлення про успішний вхід, щоб бути впевненими, що сторінка провантажилась
        wait = WebDriverWait(self.driver, 10)
        wait.until(
            EC.presence_of_element_located((By.CLASS_NAME, "flash-success"))
        )

    def register_new_user(self, email, password):
        # Відкриваємо сторінку реєстрації і заповнюємо форму
        self.driver.get(f"{BASE_URL}/register")
        self.driver.find_element(By.ID, "email").send_keys(email)
        self.driver.find_element(By.XPATH, "//input[@name='password']").send_keys(password)
        self.driver.find_element(By.NAME, "confirm_password").send_keys(password)
        
        self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        
        # Чекаємо, поки нас перекине на сторінку входу — це значить, що реєстрація пройшла успішно
        wait = WebDriverWait(self.driver, 10)
        wait.until(EC.url_contains("/login"))

    def test_1_registration_and_login(self):
        print("\n>>> Running Test 1: Registration & Login")
        
        # Генеруємо унікальну пошту, щоб база даних не сварилася на дублікати
        test_email = f"user_{int(time.time())}@selenium.com"
        test_pass = "Pass1234"

        # Спочатку реєструємося
        self.register_new_user(test_email, test_pass)

        # Перевіряємо, чи з'явилося зелене повідомлення про успіх
        try:
            success_msg = self.driver.find_element(By.CLASS_NAME, "flash-success").text
            self.assertTrue("успішна" in success_msg or "вхід" in success_msg.lower())
        except Exception:
             self.assertIn("/login", self.driver.current_url)

        # Тепер пробуємо увійти з новим акаунтом
        self.login_user(test_email, test_pass)

        # Якщо ми бачимо посилання "Профіль", значить ми точно всередині
        profile_link = self.driver.find_element(By.LINK_TEXT, "Профіль")
        self.assertIsNotNone(profile_link)

    def test_2_create_application_waits(self):
        print("\n>>> Running Test 2: Create Application")
        
        email = f"app_creator_{int(time.time())}@gmail.com"
        password = "Password123"
        
        # Щоб створити заявку, спочатку треба зареєструватись і увійти
        self.register_new_user(email, password)
        self.login_user(email, password)

        # Йдемо на сторінку створення нової заявки
        self.driver.get(f"{BASE_URL}/applications/new")

        # Про всяк випадок перевіряємо, чи нас не викинуло назад на логін
        if "/login" in self.driver.current_url:
            self.fail("Login failed or session lost, redirected to login page")

        # Заповнюємо назву та опис
        self.driver.find_element(By.ID, "title").send_keys("Selenium Auto Test App")
        self.driver.find_element(By.ID, "short_description").send_keys("Description generated by Selenium WebDriver.")
        
        self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()

        # Чекаємо, поки вискочить повідомлення, що заявка створена
        wait = WebDriverWait(self.driver, 10)
        flash_message = wait.until(
            EC.visibility_of_element_located((By.CLASS_NAME, "flash-success"))
        )

        self.assertIn("успішно створено", flash_message.text)

    def test_3_verify_table_data_xpath(self):
        print("\n>>> Running Test 3: Table Verification with XPath")
        
        email = f"table_user_{int(time.time())}@gmail.com"
        password = "Pass1234"
        
        # Стандартна процедура: новий юзер -> вхід
        self.register_new_user(email, password)
        self.login_user(email, password)
        
        # Створюємо заявку з унікальною назвою, щоб потім її знайти
        app_title = f"Unique Selenium Title {int(time.time())}"
        self.driver.get(f"{BASE_URL}/applications/new")
        self.driver.find_element(By.ID, "title").send_keys(app_title)
        self.driver.find_element(By.ID, "short_description").send_keys("Desc")
        self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        
        # Чекаємо підтвердження створення
        WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.CLASS_NAME, "flash-success"))
        )
        
        # Переходимо до списку всіх моїх заявок
        self.driver.get(f"{BASE_URL}/applications")

        # Шукаємо в таблиці рядок, де є наша унікальна назва
        target_cell = self.driver.find_element(By.XPATH, f"//td[contains(text(), '{app_title}')]")
        self.assertTrue(target_cell.is_displayed())
        
        # Перевіряємо, що поруч із цією заявкою стоїть статус "Чернетка"
        status_badge = target_cell.find_element(By.XPATH, "./..//span[contains(@class, 'status-draft')]")
        self.assertIn("Чернетка", status_badge.text)

if __name__ == "__main__":
    unittest.main()